config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  get "about" => "pages#about"

  devise_for :users

  resources :events, except: [:destroy] do
    resources :registrations, only: [:create]
    end
  resources :photos, only: [:destroy]
  resources :profiles, only: [:new, :edit, :create, :update]

  namespace :api do resources :events
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_and_belongs_to_many :events
end

app/models/event.rb
class Event < ApplicationRecord

    belongs_to :user
    has_and_belongs_to_many :categories
    has_many :photos
    has_many :registrations, dependent: :destroy
    has_many :guests, through: :registrations, source: :user

    validates :name, presence: true
    validates :description, presence: true, length: { maximum: 500 }
    # validates :starts_at, presence: true
    # validates :ends_at, presence: true, date: { after_or_equal_to:  :starts_at}

    def self.active
      where(active: true)
    end

    def bargain?
      price < 30.00
    end

    def self.order_by_price
      order :price
    end

    def self.order_by_letter
      all.sort
    end


end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event

  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord

    belongs_to :user

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :bio, presence: true

    def full_name
      "#{first_name} #{last_name}"
    end


    def self.by_initial(letter)
      where("first_name LIKE ?", "#{letter}%").order(:first_name)
    end
    
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :event
  belongs_to :user

  validates :guests_count, presence: true, numericality: {greater_than_or_equal_to: 3}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :events, dependent: :destroy
         has_one :profile
         has_many :registrations, dependent: :destroy
         has_many :visited_events, through: :registrations, source: :event

        def full_name
          return profile.full_name if profile?

          email
        end

        def profile?
          profile.present? && profile.persisted?
        end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @events = current_user.events
  end

  def show
    @events = @event.categories
    @photos = @event.photos
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      image_params.each do |image|
        @event.photos.create(image: image)
      end

      redirect_to @event, notice: "Event created"
    else
      render :new
    end
  end

  def edit
    if current_user.id == @event.user.id
      @photos = @event.photos
    else
      redirect_to root_path, notice: "You don't have permission."
    end
  end

  def update
    if @event.update(event_params)
      image_params.each do |image|
        @event.photos.create(image: image)
      end

      redirect_to edit_event_path(@event), notice: "Event updated"
    else
      render :edit
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params
    .require(:event)
    .permit(:name, :description, :location, :price, :capacity, :includes_food,
      :includes_drinks, :starts_at, :ends_at,:active, category_ids:[])
  end

  def image_params
    params[:image].present? ? params.require(:images) : []
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @event = Event.first
    @event_active = Event.active
  end

  def about
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController


  def destroy
    photo = Photo.find(params[:id])
    @event = photo.event
    if @event.user.id == current_user.id
      photo.destroy

      redirect_to edit_event_path(@event), notice: "Photo successfully removed"
    else
      redirect_to @event, notice: "Cannot delete that photo"
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController


  before_action :set_profile, only: [:edit, :update]
    before_action :authenticate_user!

    def new
      @profile = Profile.new
    end

    def create
      @profile = current_user.build_profile(profile_params)

      if @profile.save
        redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @profile.update(profile_params)
        redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
      else
        render :edit
      end
    end

    private
      def set_profile
        @profile = current_user.profile
      end

      def profile_params
        params.require(:profile).permit(:first_name, :last_name, :bio)
      end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  before_action :load_event
  before_action :authentication_user!

  def create
    @registration = current_user.registrations.create(registration_params.merge({
     event:  @event }))

    redirect_to @registration.event, notice: "Thank you for registration!"
  end

  private

  def registration_params
    params.require(:registration).permit(:status, :guests_count)
  end

  def load_event
    @event = Event.find(params[:event_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = user.events
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top navbarcollor" id="navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar">tekst</span>
        <span class="icon-bar">tekst</span>
        <span class="icon-bar">tekst</span>
      </button>
      <%= link_to "Codaisseurup", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>

            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<p>lalalala<p>

app/views/pages/home.html.erb
<h1> ~ ~ ~ W e l c o m e ~ ~ ~</h1>
  <p>Alles goed?</p>


<h2>Click on one of the buttons below</h2>
  <div class="btn-group btn-danger btn-group-lg" role="group" aria-label="...">
    <button type="button" class="btn btn-info">Home</button>
    <button type="button" class="btn btn-warning"><%= link_to "Sign-in", new_user_session_path%></button>
    <button type="button" class="btn btn-primary">Pictures</button>
  </div>

<br>
<br>
<br>

<div class="container">
  <% @event_active.each do |event|  %>
    <div class="row">
      <div class="col-lg-3"><%= event.name %></div>
      <div class="col-lg-3">Event 1<br>
        -------<br>
        met heel veel tekst<br></div>
      <div class="col-lg-3">Event 2<br>-----<br></div>
      <div class="col-lg-3">Event 3<br> -------<br></div>
    </div>
  <% end %>
  <div class="row">
    <div class="col-lg-4">---</div>
    <div class="col-lg-4">---</div>
    <div class="col-lg-4">---</div>
  </div>
</div>
<!-- <div class="artikelen">
  <p>Artikel 1</p>
  <p>Artikel 2</p>
  <p>Artikel 3</p>
</div> -->

<br>
<br>
<br>

  <div>
    <img src="../../../assets/images/IMG_0120.jpg" alt="mislukt" height="200px" width="200px">
  </div>

<br>
<br>
<br>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top" id="navbar1">
  <div class="container">
    <div class="navbar-header" id="navbar2">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Codaisseurup", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">



      <ul class="nav navbar-nav navbar-right">
         <li><%= link_to "About", about_path %></li>
        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>

            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.full_name %> <span class="caret"></span></a>

            <ul class="dropdown-menu">
              <li><%= link_to "Your Listings", events_path %></li>
              <li role="separator" class="divider"></li>

                <% if current_user.profile? %>
              <li><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></li>
                  <% else %>
              <li><%= link_to "Create Profile", new_profile_path %></li>
                  <% end %>
              <li><%= link_to "Edit Password", edit_user_registration_path %></li>

              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>

              </li>
                  <% end %>
            </ul>
    </div>
  </div>
</nav>