config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  get "about" => "pages#about"

  devise_for :users

  resources :events, except: [:destroy] do
    resources :registrations, only: [:create]
    end
  resources :photos, only: [:destroy]
  resources :profiles, only: [:new, :edit, :create, :update]

  namespace :api do resources :events
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_and_belongs_to_many :events
end

app/models/event.rb
class Event < ApplicationRecord

    belongs_to :user
    has_and_belongs_to_many :categories
    has_many :photos
    has_many :registrations, dependent: :destroy
    has_many :guests, through: :registrations, source: :user

    validates :name, presence: true
    validates :description, presence: true, length: { maximum: 500 }
    # validates :starts_at, presence: true
    # validates :ends_at, presence: true, date: { after_or_equal_to:  :starts_at}

    def self.active
      where(active: true)
    end

    def bargain?
      price < 30.00
    end

    def self.order_by_price
      order :price
    end

    def self.order_by_letter
      all.sort
    end


end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event

  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord

    belongs_to :user

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :bio, presence: true

    def full_name
      "#{first_name} #{last_name}"
    end


    def self.by_initial(letter)
      where("first_name LIKE ?", "#{letter}%").order(:first_name)
    end
    
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :event
  belongs_to :user

  validates :guests_count, presence: true, numericality: {greater_than_or_equal_to: 3}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :events, dependent: :destroy
         has_one :profile
         has_many :registrations, dependent: :destroy
         has_many :visited_events, through: :registrations, source: :event

        def full_name
          return profile.full_name if profile?

          email
        end

        def profile?
          profile.present? && profile.persisted?
        end

end

app/controllers/api/events_controller.rb
class Api::EventsController < ApplicationController

  def index
    render status: 200, json: {events: Event.all}.to_json
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @events = current_user.events
  end

  def show
    @events = @event.categories
    @photos = @event.photos
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      image_params.each do |image|
        @event.photos.create(image: image)
      end

      redirect_to @event, notice: "Event created"
    else
      render :new
    end
  end

  def edit
    if current_user.id == @event.user.id
      @photos = @event.photos
    else
      redirect_to root_path, notice: "You don't have permission."
    end
  end

  def update
    if @event.update(event_params)
      image_params.each do |image|
        @event.photos.create(image: image)
      end

      redirect_to edit_event_path(@event), notice: "Event updated"
    else
      render :edit
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params
    .require(:event)
    .permit(:name, :description, :location, :price, :capacity, :includes_food,
      :includes_drinks, :starts_at, :ends_at,:active, category_ids:[])
  end

  def image_params
    params[:image].present? ? params.require(:images) : []
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @event = Event.first
    @event_active = Event.active
  end

  def about
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController


  def destroy
    photo = Photo.find(params[:id])
    @event = photo.event
    if @event.user.id == current_user.id
      photo.destroy

      redirect_to edit_event_path(@event), notice: "Photo successfully removed"
    else
      redirect_to @event, notice: "Cannot delete that photo"
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController


  before_action :set_profile, only: [:edit, :update]
    before_action :authenticate_user!

    def new
      @profile = Profile.new
    end

    def create
      @profile = current_user.build_profile(profile_params)

      if @profile.save
        redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @profile.update(profile_params)
        redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
      else
        render :edit
      end
    end

    private
      def set_profile
        @profile = current_user.profile
      end

      def profile_params
        params.require(:profile).permit(:first_name, :last_name, :bio)
      end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  before_action :load_event
  before_action :authentication_user!

  def create
    @registration = current_user.registrations.create(registration_params.merge({
     event:  @event }))

    redirect_to @registration.event, notice: "Thank you for registration!"
  end

  private

  def registration_params
    params.require(:registration).permit(:status, :guests_count)
  end

  def load_event
    @event = Event.find(params[:event_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = user.events
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: { multipart: true } do |f| %>

  <div class="form-group">
    <label>Listing name</label>
    <%= f.text_field :name, placeholder: "Listing name of event", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Description</label>
    <%= f.text_area :description, rows: 5, placeholder: "Say something about this event", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Location</label>
    <%= f.select :location, [["Amsterdam","Amstardam"], ["Kiev", "Kiev"], ["Diemen", "Diemen"]], prompt: "Select the sity", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Price</label>
    <div class="input-group">
      <div class="input-group-addon">€</div>
      <%= f.number_field :price, placeholder: "per person", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label>Capacity</label>
    <div class="input-group">
      <div class="input-group-addon"></div>
      <%= f.number_field :price, placeholder: "not more than 30 persons", class: "form-control" %>
    </div>
  </div>

  <label>Categories</label>

<%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
  <div class="form-group">
    <%= b.check_box(class: "check_box") %> <%= b.object.name %>
  </div>
<% end %>

  <div class="form-group">
    <%= f.check_box :includes_food %> Foods includes?
  </div>

  <div class="form-group">
    <%= f.check_box :includes_drinks %> Drinks includes?
  </div>

  <div class="form-group">
    <label> Date of event (starts) </label>
    <%= f.datetime_select :starts_at, placeholder: "Event starts at:", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Date of event (ends)</label>
    <%= f.datetime_select :ends_at, placeholder: "Event ends at:", class: "form-control" %>
  </div>

  <label>Photos</label>
  <div class="form-group">
    <span class="btn btn-default" id="form">
      Upload photos
      <%= file_field_tag "images[]", type: :file, multiple: true %>
    </span>
  </div>

  <div id="photos">
    <%= render 'photos/list' %>
  </div>

  <label>Publish this place?</label>

  <div class="form-group">
    <%= f.check_box :active %> Active
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>



<% end %>

app/views/events/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit place
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<div class="row">
  <div class="col-md-3" id="lijstlinks">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", events_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", events_path, class: "sidebar-link" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-primary" id="listings">
      <div class="panel-heading">
        Your Listings
      </div>
      <div class="panel-body">

        <% @events.each do |event| %>
        <div class="row">
          <div class="col-md-7">
            <h4><%= event.name %></h4>
          </div>
          <div class="col-md-3 right">
            <%= link_to "View", event, class: "btn btn-default" %>
            <%= link_to "Update", edit_event_path(event), class: "btn btn-default" %>
          </div>
        </div>
        <% end %>

      </div>
    </div>

    <%= link_to "Add new place", new_event_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/events/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add a new place
  </div>

  <div class="panel-body" id="listings">
    <%= render 'form' %>
  </div>
  
</div>

app/views/events/show.html.erb
<% if current_user != @event.user %>
  <div class="panel panel-primary">
    <div class="panel-heading">Register for this event</div>

    <div class="panel-body">
      <%= render 'registrations/form' %>
    </div>
  </div>
<% end %>



<div class="panel panel-primary">
  <div class="panel-heading"><%= @event.name %></div>

  <div class="panel-body">

    <p>Address: <%= @event.location %></p>
    <p>Host: <%= @event.user.email %></p>

    <!-- Main Info -->
    <h4>Main Info</h4>
    <p>Home Type: <%= @event.name %></p>
    <p><%= @event.location %> <%= @event.price > 1 ? "Guests" : "Guest" %></p>

    <!-- About -->
    <h4>About</h4>
    <p><%= @event.description %></p>

    <!-- Amenities -->
    <h4>Amenities</h4>
    <ul class="amenities">
      <li><%= !@event.includes_food ? ("<s>Food</s>").html_safe : "Food" %></li>
      <li><%= !@event.includes_drinks ? ("<del>Drinks</del>").html_safe : "Drinks" %></li>
    </ul>

  </div>

</div>

<%= link_to "Back", events_path, class: "btn btn-default" %>

<h4>Themes</h4>
<% @events.each do |category| %>
  <span class="label label-success"><%= category.name %></span>
<% end %>

<h4>Photos</h4>
<% @event.photos.each do |photo| %>
<div class="panel panel-default">
  <div class="panel-heading">
    <%= image_tag photo.image.thumbnail %>
  </div>
</div>
<% end %>

app/views/photos/_list.html.erb
<% if @photos %>
  <% @photos.each do |photo| %>
    <div class="panel panel-default">
      <div class="panel-heading preview">
        <%= image_tag photo.image.thumbnail %>
      </div>
      <div class="panel-body">Delete
    </div>
  <% end %>
<% end %>

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
  <% @profile.errors.full_messages.each do |msg| %>
    <p class="alert alert-danger"><%= msg %></p>
  <% end %>

  <div class="form-group">
    <label>First Name</label>
    <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Last Name</label>
    <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Bio</label>
    <%= f.text_area :bio, rows: 5, placeholder: "Say something about yourself", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Back", root_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Edit your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Create your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>